export const tnDistricts = {
    'Ariyalur': ['Ariyalur Town', 'Jayankondam', 'Sendurai', 'Udayarpalayam'],
    'Chengalpattu': ['Tambaram', 'Chengalpattu Town', 'Guduvancheri', 'Madurantakam'],
    'Chennai': ['T Nagar', 'Velachery', 'Anna Nagar', 'Adyar'],
    'Coimbatore': ['Gandhipuram', 'RS Puram', 'Peelamedu', 'Saravanampatti'],
    'Cuddalore': ['Cuddalore Town', 'Chidambaram', 'Neyveli', 'Panruti'],
    'Dharmapuri': ['Dharmapuri Town', 'Harur', 'Palacode', 'Pennagaram'],
    'Dindigul': ['Dindigul Town', 'Palani', 'Oddanchatram', 'Nilakottai'],
    'Erode': ['Erode Town', 'Perundurai', 'Gobichettipalayam', 'Bhavani'],
    'Kallakurichi': ['Kallakurichi Town', 'Ulundurpet', 'Sankarapuram', 'Chinnasalem'],
    'Kanchipuram': ['Kanchipuram Town', 'Sriperumbudur', 'Walajabad', 'Uthiramerur'],
    'Kanniyakumari': ['Nagercoil', 'Marthandam', 'Colachel', 'Kanyakumari'],
    'Karur': ['Karur Town', 'Kulithalai', 'Aravakurichi', 'Krishnarayapuram'],
    'Krishnagiri': ['Krishnagiri Town', 'Hosur', 'Denkanikottai', 'Bargur'],
    'Madurai': ['KK Nagar', 'Mattuthavani', 'Thirunagar', 'Goripalayam'],
    'Mayiladuthurai': ['Mayiladuthurai Town', 'Sirkazhi', 'Kuthalam', 'Tharangambadi'],
    'Nagapattinam': ['Nagapattinam Town', 'Velankanni', 'Kilvelur', 'Thirukkuvalai'],
    'Namakkal': ['Namakkal Town', 'Tiruchengode', 'Rasipuram', 'Paramathi Velur'],
    'Nilgiris': ['Ooty', 'Coonoor', 'Kotagiri', 'Gudalur'],
    'Perambalur': ['Perambalur Town', 'Kunnam', 'Veppanthattai', 'Alathur'],
    'Pudukkottai': ['Pudukkottai Town', 'Thirumayam', 'Aranthangi', 'Avudaiyarkoil'],
    'Ramanathapuram': ['Ramanathapuram Town', 'Paramakudi', 'Rameswaram', 'Keelakarai'],
    'Ranipet': ['Ranipet', 'Arcot', 'Walajah', 'Sholingur'],
    'Salem': ['Salem Town', 'Hasthampatti', 'Ammapet', 'Omalur'],
    'Sivaganga': ['Sivaganga Town', 'Karaikudi', 'Devakottai', 'Manamadurai'],
    'Tenkasi': ['Tenkasi Town', 'Courtallam', 'Sankarankovil', 'Kadayanallur'],
    'Thanjavur': ['Thanjavur Town', 'Kumbakonam', 'Pattukkottai', 'Thiruvaiyaru'],
    'Theni': ['Theni Town', 'Bodinayakanur', 'Periyakulam', 'Uthamapalayam'],
    'Thoothukudi': ['Thoothukudi Town', 'Tiruchendur', 'Kovilpatti', 'Sathankulam'],
    'Tiruchirappalli': ['Trichy Town', 'Srirangam', 'Thillai Nagar', 'Lalgudi'],
    'Tunelveli': ['Tirunelveli Town', 'Palayamkottai', 'Ambasamudram', 'Nanguneri'],
    'Tirupattur': ['Tirupattur Town', 'Ambur', 'Vaniyambadi', 'Natrampalli'],
    'Tiruppur': ['Tiruppur Town', 'Avinashi', 'Palladam', 'Dharapuram'],
    'Tiruvallur': ['Tiruvallur Town', 'Avadi', 'Ponneri', 'Gummidipoondi'],
    'Tiruvannamalai': ['Tiruvannamalai Town', 'Arani', 'Polur', 'Chengam'],
    'Tiruvarur': ['Tiruvarur Town', 'Mannargudi', 'Thiruthuraipoondi', 'Kodavasal'],
    'Vellore': ['Vellore Town', 'Katpadi', 'Gudiyatham', 'Pernambut'],
    'Viluppuram': ['Viluppuram Town', 'Tindivanam', 'Gingee', 'Kallakurichi'],
    'Virudhunagar': ['Virudhunagar Town', 'Sivakasi', 'Rajapalayam', 'Srivilliputhur']
};
